// Алфавит
export const GEO_ALPHA = ["ა","ბ","გ","დ","ე","ვ","ზ","თ","ი","კ","ლ","მ","ნ","ო","პ","ჟ","რ","ს","ტ","უ","ფ","ქ","ღ","ყ","შ","ჩ","ც","ძ","წ","ჭ","ხ","ჯ","ჰ","ჸ"];

// Темы (категории)
export const TOPICS = [
  {key:"all",          ru:"Все",           ge:"ყველა",        en:"All",           icon:"📖"},
  {key:"family",       ru:"Семья",         ge:"ოჯახი",        en:"Family",        icon:"👨‍👩‍👧"},
  {key:"greetings",    ru:"Приветствия",   ge:"მისალმება",    en:"Greetings",     icon:"👋"},
  {key:"pronouns",     ru:"Местоимения",   ge:"ნაცვალსახ.",   en:"Pronouns",      icon:"🗣️"},
  {key:"nature",       ru:"Природа",       ge:"ბუნება",       en:"Nature",        icon:"🌿"},
  {key:"plants",       ru:"Растения",      ge:"მცენარეები",   en:"Plants",        icon:"🌱"},
  {key:"animals",      ru:"Животные",      ge:"ცხოველები",    en:"Animals",       icon:"🐾"},
  {key:"food",         ru:"Еда",           ge:"საჭმელი",      en:"Food",          icon:"🍞"},
  {key:"society",      ru:"Общество",      ge:"საზოგადოება",  en:"Society",       icon:"🏙️"},
  {key:"time_place",   ru:"Время/место",   ge:"დრო/ადგილი",   en:"Time & Place",  icon:"🕐"},
  {key:"language",     ru:"Язык",          ge:"ენა",          en:"Language",      icon:"💬"},
  {key:"descriptions", ru:"Описания",      ge:"აღწერა",       en:"Descriptions",  icon:"✨"},
  {key:"home",         ru:"Дом",           ge:"სახლი",        en:"Home",          icon:"🏠"},
  {key:"body",         ru:"Тело",           ge:"სხეული",       en:"Body",          icon:"🫀"},
  {key:"numbers",      ru:"Числа",         ge:"რიцხვები",     en:"Numbers",       icon:"🔢"},
];

// Словарь
export const DICT = [
  // ── МЕСТОИМЕНИЯ ─────────────────────────────────────────────────
  {topic:"pronouns", meg:"მა",         tr:"ma",          geo:"მე",                          ru:"я",                                   en:"I"},
  {topic:"pronouns", meg:"სი",         tr:"si",          geo:"შენ",                         ru:"ты",                                  en:"you"},
  {topic:"pronouns", meg:"თინა",       tr:"tina",        geo:"ის",                          ru:"он / она",                            en:"he / she"},
  {topic:"pronouns", meg:"ჩქი",         tr:"čki",         geo:"ჩვენ",                        ru:"мы",                                  en:"we"},
  {topic:"pronouns", meg:"თქვა",       tr:"tkva",        geo:"თქვენ",                       ru:"вы",                                  en:"you (pl.)"},
  {topic:"pronouns", meg:"თინეფი",     tr:"tinepi",      geo:"ისინი",                       ru:"они",                                 en:"they"},
  {topic:"pronouns", meg:"ათე",        tr:"ate",         geo:"ეს",                          ru:"этот",                                en:"this"},
  {topic:"pronouns", meg:"ათეგვარი",   tr:"ategvari",    geo:"ამგვარი, ამნაირი",            ru:"такой",                               en:"such, that kind"},

  // ── ПРИВЕТСТВИЯ ──────────────────────────────────────────────────
  {topic:"greetings", meg:"გომორძგუა", tr:"gomorʒgua",   geo:"გამარჯობა",                   ru:"здравствуй",                          en:"hello"},
  {topic:"greetings", meg:"მარდობა",   tr:"mardoba",     geo:"მადლობა",                     ru:"спасибо",                             en:"thank you"},
  {topic:"greetings", meg:"ბოდიში",    tr:"bodiši",      geo:"ბოდიში",                      ru:"извините",                            en:"excuse me"},

  // ── СЕМЬЯ ────────────────────────────────────────────────────────
  {topic:"family", meg:"მახორობა",   tr:"maxoroba",    geo:"ოჯახი",                       ru:"семья",                               en:"family"},
  {topic:"family", meg:"დიდა",       tr:"dida",        geo:"დედა",                        ru:"мать",                                en:"mother"},
  {topic:"family", meg:"მუმა",       tr:"muma",        geo:"მამა",                        ru:"отец",                                en:"father"},
  {topic:"family", meg:"ბაბა",       tr:"baba",        geo:"მამა",                        ru:"папаша; обращение отца к сыну",       en:"papa; daddy"},
  {topic:"family", meg:"ჯიმა",       tr:"ǯima",        geo:"ძმა",                         ru:"брат",                                en:"brother"},
  {topic:"family", meg:"და",         tr:"da",          geo:"და",                          ru:"сестра",                              en:"sister"},
  {topic:"family", meg:"სკუა",       tr:"skua",        geo:"შვილი",                       ru:"ребёнок, дитя",                       en:"child"},
  {topic:"family", meg:"ბოში",       tr:"boši",        geo:"ბიჭი, ვაჟი",                 ru:"мальчик, юноша; сын",                 en:"boy, young man; son"},
  {topic:"family", meg:"ოსურსკუა",   tr:"osurskua",    geo:"ქალიშვილი",                   ru:"дочь",                                en:"daughter"},
  {topic:"family", meg:"მოთა",       tr:"mota",        geo:"შვილიშვილი",                  ru:"внук / внучка",                       en:"grandchild"},
  {topic:"family", meg:"ბაბუ",       tr:"babu",        geo:"ბაბუა, პაპა",                ru:"дедушка; предок",                     en:"grandfather; ancestor"},
  {topic:"family", meg:"ბები",       tr:"bebi",        geo:"ბებია",                       ru:"бабушка",                             en:"grandmother"},
  {topic:"family", meg:"ჯიმადი",     tr:"ǯimadi",      geo:"ბიძა",                        ru:"дядя",                                en:"uncle"},
  {topic:"family", meg:"დეიდა",      tr:"deida",       geo:"დეიდა",                       ru:"тётя (сестра матери)",                en:"aunt (mother's sister)"},
  {topic:"family", meg:"მამიდა",     tr:"mamida",      geo:"მამიდა",                      ru:"ტётя (сестра отца)",                  en:"aunt (father's sister)"},
  {topic:"family", meg:"ბიძისკუა",   tr:"biʒiskua",    geo:"ბიძაშვილი",                   ru:"двоюродный брат/сестра",              en:"cousin"},
  {topic:"family", meg:"ქომონჯი",    tr:"komonǯi",     geo:"ქმარი",                       ru:"муж",                                 en:"husband"},
  {topic:"family", meg:"ოსური",      tr:"osuri",       geo:"ცოლი",                        ru:"жена",                                en:"wife"},
  {topic:"family", meg:"დიანთილი",   tr:"diantili",    geo:"დედამთილი",                   ru:"свекровь",                            en:"mother-in-law"},
  {topic:"family", meg:"მუანთილი",   tr:"muantili",    geo:"მამამთილი",                   ru:"свёкор",                              en:"father-in-law"},
  {topic:"family", meg:"ნათესე",     tr:"natese",      geo:"ნათესავი",                    ru:"родственник",                         en:"relative"},
  {topic:"family", meg:"ბაღანა",     tr:"bağana",      geo:"ბავშვი, ბალღი",              ru:"ребёнок",                             en:"child, infant"},
  {topic:"family", meg:"ბაღანობა",   tr:"bağanoba",    geo:"ბავშვობა",                    ru:"детство",                             en:"childhood"},

  // ── ПРИРОДА ──────────────────────────────────────────────────────
  {topic:"nature", meg:"ბალა",       tr:"bala",        geo:"ბორცვი",                      ru:"холм",                                en:"hill"},
  {topic:"nature", meg:"ბორია",      tr:"boria",       geo:"ქარი; ქარიშხალი",            ru:"ветер; буря",                         en:"wind; storm"},
  {topic:"nature", meg:"ბჟალამი",    tr:"bžalami",     geo:"მზიანი",                      ru:"солнечный (день)",                    en:"sunny (day)"},
  {topic:"nature", meg:"ბჟალარა",    tr:"bžalara",     geo:"მზის სხივი",                  ru:"солнечный луч",                       en:"sunbeam; sunny side"},
  {topic:"nature", meg:"ბუნება",     tr:"buneba",      geo:"ბუნება",                      ru:"природа",                             en:"nature"},
  {topic:"nature", meg:"დაჩხირი",    tr:"dačxiri",     geo:"ცეცხლი; ხანძარი",            ru:"огонь, пожар",                        en:"fire"},
  {topic:"nature", meg:"ქუა",        tr:"kua",         geo:"ქვა",                         ru:"камень",                              en:"stone"},

  // ── РАСТЕНИЯ ─────────────────────────────────────────────────────
  {topic:"plants", meg:"აბუჩეჩი",    tr:"abučeči",     geo:"მცენარის ერთ-ერთი სახეობა",  ru:"род травы (ботан.)",                  en:"a type of plant (bot.)"},
  {topic:"plants", meg:"ასკილი",     tr:"askili",      geo:"ასკილი",                      ru:"шиповник, дикая роза",                en:"wild rose, briar"},
  {topic:"plants", meg:"ბამბе",      tr:"bambe",       geo:"ბამბა",                       ru:"хлопок, вата",                        en:"cotton, wadding"},
  {topic:"plants", meg:"ბია",        tr:"bia",         geo:"კომში",                       ru:"айва",                                en:"quince"},
  {topic:"plants", meg:"ბინეხი",     tr:"binexi",      geo:"ვენახი, ვაზი",               ru:"виноградник, виноградная лоза",       en:"vineyard; grapevine"},
  {topic:"plants", meg:"ბული",       tr:"buli",        geo:"ბალი",                        ru:"черешня",                             en:"cherry"},
  {topic:"plants", meg:"ოდიარე",     tr:"odiare",      geo:"ბალახი",                      ru:"трава",                               en:"grass"},

  // ── ЖИВОТНЫЕ ─────────────────────────────────────────────────────
  {topic:"animals", meg:"გენი",      tr:"geni",        geo:"ხბო",                         ru:"телёнок",                             en:"calf"},
  {topic:"animals", meg:"გერი",      tr:"geri",        geo:"მგელი",                       ru:"волк",                                en:"wolf"},
  {topic:"animals", meg:"გირინი",    tr:"girini",      geo:"ვირი",                        ru:"осёл",                                en:"donkey"},
  {topic:"animals", meg:"ქოთომი",    tr:"kotomi",      geo:"ქათამი",                      ru:"курица",                              en:"hen"},
  {topic:"animals", meg:"ხოჯი",      tr:"xoǯi",        geo:"ხარი",                        ru:"бык",                                 en:"bull"},

  // ── ЕДА ──────────────────────────────────────────────────────────
  {topic:"food", meg:"ატამა",        tr:"atama",       geo:"ატამი",                       ru:"персик",                              en:"peach"},
  {topic:"food", meg:"ბჟა",          tr:"bža",         geo:"რძე",                         ru:"молоко",                              en:"milk"},
  {topic:"food", meg:"ბურახი",       tr:"buraxi",      geo:"კვასი",                       ru:"квас",                                en:"kvass"},
  {topic:"food", meg:"გემო",         tr:"gemo",        geo:"გემო",                        ru:"вкус",                                en:"taste, flavour"},
  {topic:"food", meg:"გემუანი",      tr:"gemuani",     geo:"გემრიელი",                    ru:"вкусный",                             en:"tasty, delicious"},
  {topic:"food", meg:"ქობალი",       tr:"kobali",      geo:"პური",                        ru:"хлеб",                                en:"bread"},
  {topic:"food", meg:"სადილი",       tr:"sadili",      geo:"სადილი",                      ru:"обед",                                en:"lunch, dinner"},

  // ── ОБЩЕСТВО ─────────────────────────────────────────────────────
  {topic:"society", meg:"აბაზი",     tr:"abazi",       geo:"აბაზი, ოცი კაპიკი",          ru:"двугривенный, двадцать копеек",       en:"twenty kopecks"},
  {topic:"society", meg:"აბაშური",   tr:"abašuri",     geo:"1. აბაშელი 2. აბაშური",      ru:"1. абашец 2. абашский",               en:"1. person from Abasha 2. of Abasha"},
  {topic:"society", meg:"აბრაგალა",  tr:"abragala",    geo:"აბრაგად ყოფნა, აბრაგობა",    ru:"абречество, разбойничество",          en:"brigandage, outlaw life"},
  {topic:"society", meg:"აბრაგი",    tr:"abragi",      geo:"აბრაგი",                      ru:"абрек, разбойник",                    en:"abrek, brigand"},
  {topic:"society", meg:"აგაგა",     tr:"agaga",       geo:"მოჩვენება, ლანდი; ჩონჩხი",   ru:"привидение, призрак; скелет",         en:"ghost, apparition; skeleton"},
  {topic:"society", meg:"აგვართა",   tr:"agvarta",     geo:"ბრბო, თაყარილობა",            ru:"масса, толпа",                        en:"mass, crowd"},
  {topic:"society", meg:"ადამიანი",  tr:"adamiani",    geo:"ადამიანი, გადატ. ქალი",       ru:"человек; перен. женщина",             en:"person; fig. woman"},
  {topic:"society", meg:"ბაზარი",    tr:"bazari",      geo:"ბაზარი",                      ru:"базар",                               en:"market, bazaar"},
  {topic:"society", meg:"ბერი",      tr:"beri",        geo:"ბერი",                        ru:"монах",                               en:"monk"},
  {topic:"society", meg:"ბობოხი",    tr:"boboxi",      geo:"ხმამაღალი ლაპარაკი",          ru:"громкий разговор",                    en:"loud talk"},
  {topic:"society", meg:"ბობოხია",   tr:"bobobia",     geo:"მხვეწარი, ამპარტავანი",       ru:"хвастун",                             en:"boaster, braggart"},
  {topic:"society", meg:"ბოშიკათა",  tr:"bošiḳata",    geo:"ახალგაზრდობა",                ru:"молодёжь",                            en:"youth (collective)"},
  {topic:"society", meg:"გემი",      tr:"gemi",        geo:"გემი",                        ru:"корабль",                             en:"ship"},
  {topic:"society", meg:"კოჩი",      tr:"ḳoči",        geo:"ადამიანი",                    ru:"человек",                             en:"person"},
  {topic:"society", meg:"ნოღა",      tr:"noğa",        geo:"ქალაქი",                      ru:"город",                               en:"city"},
  {topic:"society", meg:"სოფელი",    tr:"sopeli",      geo:"სოფელი",                      ru:"село",                                en:"village"},
  {topic:"society", meg:"ქიანა",     tr:"kiana",       geo:"ქვეყანა",                     ru:"страна",                              en:"country"},
  {topic:"society", meg:"ხარხი",     tr:"xarxi",       geo:"ხალხი",                       ru:"народ, люди",                         en:"people, folk"},

  // ── ВРЕМЯ И МЕСТО ────────────────────────────────────────────────
  {topic:"time_place", meg:"აბანი",   tr:"abani",       geo:"ადგილი",                      ru:"место",                               en:"place"},
  {topic:"time_place", meg:"აბაშა",   tr:"abaša",       geo:"აბაშა (სოფელი, მდინარე)",     ru:"Абаша (село и река в Мегрелии)",      en:"Abasha (village and river in Mingrelia)"},
  {topic:"time_place", meg:"აბჟუა",   tr:"abžua",   dialect:"sam",       geo:"აფხაზეთი",                    ru:"Абхазия",                             en:"Abkhazia"},
  {topic:"time_place", meg:"ადრე",    tr:"adre",        geo:"ადრე",                        ru:"рано",                                en:"early"},
  {topic:"time_place", meg:"ამდღა",   tr:"amdğa",       geo:"დღეს",                        ru:"сегодня",                             en:"today"},
  {topic:"time_place", meg:"ამნიჯი",  tr:"amniǯi",      geo:"ამ საღამოს",                  ru:"этим вечером",                        en:"this evening"},
  {topic:"time_place", meg:"აპრილი",  tr:"aprili",      geo:"აპრილი",                      ru:"апрель",                              en:"April"},
  {topic:"time_place", meg:"არგუსო",  tr:"arguso",      geo:"აგვისტო",                     ru:"август",                              en:"August"},
  {topic:"time_place", meg:"არდგილი", tr:"ardgili",     geo:"ადგილი",                      ru:"место",                               en:"place"},
  {topic:"time_place", meg:"ართიალამო",tr:"artialamo",  geo:"ერთბაშად",                    ru:"сразу",                               en:"at once, immediately"},
  {topic:"time_place", meg:"ართიშა",  tr:"artiša",      geo:"ერთხელ",                      ru:"однажды, один раз",                   en:"once, one time"},
  {topic:"time_place", meg:"ართო",    tr:"arto",        geo:"ერთად",                       ru:"вместе",                              en:"together"},
  {topic:"time_place", meg:"ასე",     tr:"ase",         geo:"ახლა",                        ru:"теперь, ныне",                        en:"now"},
  {topic:"time_place", meg:"ბჟადალი", tr:"bžadali",     geo:"დასავლეთი",                   ru:"запад",                               en:"west"},
  {topic:"time_place", meg:"ბჟაიოლუ", tr:"bžaiolu",    geo:"აღმოსავლეთი",                 ru:"восток",                              en:"east"},
  {topic:"time_place", meg:"გაზაფხული",tr:"gazapxuli",  geo:"გაზაფხული",                   ru:"весна",                               en:"spring"},
  {topic:"time_place", meg:"სათი",    tr:"sati",        geo:"საათი",                       ru:"час, часы",                           en:"hour, clock"},
  {topic:"time_place", meg:"სო",      tr:"so",          geo:"სად",                         ru:"где",                                 en:"where"},

  // ── ЯЗЫК И ОБЩЕНИЕ ───────────────────────────────────────────────
  {topic:"language", meg:"აბა!",      tr:"aba",         geo:"აბა!",                        ru:"ну-ка! да! ну!",                      en:"come on! hey!"},
  {topic:"language", meg:"ამბე",      tr:"ambe",        geo:"ამბავი",                      ru:"весть, история, известие",            en:"news, tidings"},
  {topic:"language", meg:"ანგელოზი",  tr:"angelozi",    geo:"ანგელოზი",                    ru:"ангел",                               en:"angel"},
  {topic:"language", meg:"არიკი",     tr:"ariki",       geo:"ზღაპარი",                     ru:"сказка",                              en:"fairy tale"},
  {topic:"language", meg:"გვარი",     tr:"gvari",       geo:"გვარი",                       ru:"фамилия",                             en:"surname"},
  {topic:"language", meg:"გურაფა",    tr:"gurapa",      geo:"სწავლა",                      ru:"учёба",                               en:"study"},
  {topic:"language", meg:"ნინა",      tr:"nina",        geo:"ენა",                         ru:"язык",                                en:"language"},
  {topic:"language", meg:"სახელი",    tr:"saxeli",      geo:"სახელი",                      ru:"имя",                                 en:"name"},

  // ── ОПИСАНИЯ ─────────────────────────────────────────────────────
  {topic:"descriptions", meg:"აბორჯება",  tr:"aborǯeba",  dialect:"sen",  geo:"აბნევა, დაბნევა",           ru:"растеряться",                         en:"to get confused"},
  {topic:"descriptions", meg:"აბორჯებული",tr:"aborǯebuli",dialect:"sen",geo:"დაბნეული",                  ru:"растерянный; рассеянный",             en:"confused; absent-minded"},
  {topic:"descriptions", meg:"ადვილო",    tr:"advilo",    geo:"ადვილად",                   ru:"легко (нареч.)",                      en:"easily"},
  {topic:"descriptions", meg:"ამუნათი",   tr:"amunati",   geo:"ლამაზი, საუკეთესო",         ru:"прекрасный",                          en:"beautiful, wonderful"},
  {topic:"descriptions", meg:"ბედი",      tr:"bedi",      geo:"ბედი",                      ru:"судьба, счастье, участь",             en:"fate, destiny"},
  {topic:"descriptions", meg:"ბედნიერება",tr:"bedniereba",geo:"ბედნიერება",                ru:"счастье",                             en:"happiness"},
  {topic:"descriptions", meg:"ბედნიერი",  tr:"bednieri",  geo:"ბედნიერი",                  ru:"счастливый",                          en:"happy, fortunate"},
  {topic:"descriptions", meg:"ბეხვერია",  tr:"bexveria",  geo:"ფუმფულა, ფუნჩულა",         ru:"пухлый, пышный",                      en:"chubby, plump"},
  {topic:"descriptions", meg:"ბეჯითი",    tr:"beǯiti",    geo:"ბეჯითი, მუყაითი",          ru:"прилежный",                           en:"diligent, assiduous"},
  {topic:"descriptions", meg:"ბოლო",      tr:"bolo",      geo:"ბოლო",                      ru:"конец",                               en:"end"},
  {topic:"descriptions", meg:"ბონი",      tr:"boni",      geo:"პირდაპირი, სწორი",          ru:"прямой; ровный",                      en:"straight; level, even"},
  {topic:"descriptions", meg:"ბრელი",     tr:"breli",     geo:"ბევრი",                     ru:"много",                               en:"many, much"},
  {topic:"descriptions", meg:"ჰამო",      tr:"hamo",      geo:"სასიამოვნო, ტკბილი",        ru:"приятный, сладкий",                   en:"pleasant, sweet"},

  // ── ДОМ ──────────────────────────────────────────────────────────
  {topic:"home", meg:"აბანა",         tr:"abana",       geo:"1. აბანო 2. სამკურნალო წყლები", ru:"1. баня 2. лечебные воды",         en:"1. bath 2. medicinal waters"},
  {topic:"home", meg:"აბარწა",        tr:"abarc̣a",     dialect:"sam",     geo:"ჟირმალი; ლია აივანი",         ru:"крыльцо; открытый балкон",            en:"porch; open balcony"},
  {topic:"home", meg:"აგაფა",         tr:"agapa",       dialect:"sam",       geo:"კვეტო",                       ru:"соха (сам.)",                         en:"plow (Samurz. dial.)"},
  {topic:"home", meg:"აგვარა",        tr:"agvara",      geo:"1. ბაკი 2. ბოსელი, გომური",  ru:"1. скотный двор 2. хлев",             en:"1. cattle yard 2. barn"},
  {topic:"home", meg:"აკошკა",        tr:"aḳošḳa",     geo:"ფანჯარა",                     ru:"окно",                                en:"window"},
  {topic:"home", meg:"ბალიში",        tr:"bališi",      geo:"ბალიში",                      ru:"подушка",                             en:"pillow"},
  {topic:"home", meg:"ბარბალი",       tr:"barbali",     geo:"ბორბალი",                     ru:"колесо",                              en:"wheel"},
  {topic:"home", meg:"ბარგი",         tr:"bargi",       geo:"სამოსი, ბარგი",               ru:"одежда; вещи, багаж",                 en:"clothes; belongings"},
  {topic:"home", meg:"ბიგა",          tr:"biga",        geo:"ჯოხი",                        ru:"палка",                               en:"stick, rod"},
  {topic:"home", meg:"ბოთოლი",        tr:"botoli",      geo:"ბოთლი",                       ru:"бутылка",                             en:"bottle"},
  {topic:"home", meg:"ბუმბული",       tr:"bumbuli",     geo:"ბუმბული",                     ru:"перина, пуховик",                     en:"feather duvet"},
  {topic:"home", meg:"ბუხარი",        tr:"buxari",      geo:"ბუხარი",                      ru:"камин",                               en:"fireplace"},
  {topic:"home", meg:"ბურთი",         tr:"burti",       geo:"ბურთი",                       ru:"мяч, шарик",                          en:"ball"},
  {topic:"home", meg:"კარი",          tr:"ḳari",        geo:"კარი",                        ru:"дверь",                               en:"door"},
  {topic:"home", meg:"კიდალა",        tr:"ḳidala",      geo:"კედელი",                      ru:"стена",                               en:"wall"},
  {topic:"home", meg:"კრესლო",        tr:"ḳreslo",      geo:"სავარძელი",                   ru:"кресло",                              en:"armchair"},
  {topic:"home", meg:"ონჯირალი",      tr:"onǯirali",    geo:"საძინებელი",                  ru:"спальня",                             en:"bedroom"},
  {topic:"home", meg:"ორთვალი",       tr:"ortvali",     geo:"სახურავი",                    ru:"крыша",                               en:"roof"},
  {topic:"home", meg:"პроლი",         tr:"p̣roli",      geo:"იატაკი",                      ru:"пол",                                 en:"floor"},
  {topic:"home", meg:"სტოლი",         tr:"stoli",       geo:"მაგიდა",                      ru:"стол",                                en:"table"},
  {topic:"home", meg:"ტყვა",          tr:"ṭq̣va",       geo:"კიბе",                        ru:"лестница",                            en:"staircase"},
  {topic:"home", meg:"ღობერი",        tr:"ğoberi",      geo:"ღობე",                        ru:"забор",                               en:"fence"},
  {topic:"home", meg:"ჸუდე",          tr:"ʼude",        geo:"სახლი",                       ru:"дом",                                 en:"house"},

  // ── ТЕЛО ─────────────────────────────────────────────────────────
  {topic:"body", meg:"დუდი",       tr:"dudi",        geo:"თავი",                        ru:"голова",                              en:"head"},
  {topic:"body", meg:"ჸვა",        tr:"ʼva",         geo:"შუბლი",                       ru:"лоб",                                 en:"forehead"},
  {topic:"body", meg:"თოლი",       tr:"toli",         geo:"თვალი",                       ru:"глаз",                                en:"eye"},
  {topic:"body", meg:"თომა",       tr:"toma",         geo:"თმა",                         ru:"волосы",                              en:"hair",        dialects:{sen:{meg:"თომა",tr:"toma"},sam:{meg:"თუმა",tr:"tuma"}}},
  {topic:"body", meg:"წაბი",       tr:"c̣abi",        geo:"წარბი",                       ru:"бровь",                               en:"eyebrow"},
  {topic:"body", meg:"წიმორთი",    tr:"c̣imorti",     geo:"ნაკუთალი (წვივისა)",          ru:"икра (ноги)",                         en:"calf (of leg)"},
  {topic:"body", meg:"წყურკუჩხი",  tr:"c̣q̣urkučxi",  geo:"კოჭი",                        ru:"лодыжка",                             en:"ankle",          dialect:"sam"},

  // ── ЧИСЛА ────────────────────────────────────────────────────────
  {topic:"numbers", num:1,    meg:"ართი",       tr:"arti",        geo:"ერთი",                        ru:"один",                                en:"one"},
  {topic:"numbers", num:2,    meg:"ჟირი",       tr:"žiri",        geo:"ორი",                         ru:"два",                                 en:"two"},
  {topic:"numbers", num:3,    meg:"სუმი",       tr:"sumi",        geo:"სამი",                        ru:"три",                                 en:"three"},
  {topic:"numbers", num:4,    meg:"ოთხი",       tr:"otxi",        geo:"ოთხი",                        ru:"четыре",                              en:"four"},
  {topic:"numbers", num:5,    meg:"ხუთი",       tr:"xuti",        geo:"ხუთი",                        ru:"пять",                                en:"five"},
  {topic:"numbers", num:6,    meg:"ამშვი",      tr:"amšvi",       geo:"ექვსი",                       ru:"шесть",                               en:"six"},
  {topic:"numbers", num:7,    meg:"შკვითი",     tr:"škviti",      geo:"შვიდი",                       ru:"семь",                                en:"seven"},
  {topic:"numbers", num:8,    meg:"რუო",        tr:"ruo",         geo:"რვა",                         ru:"восемь",                              en:"eight"},
  {topic:"numbers", num:9,    meg:"ჩხორო",      tr:"čxoro",       geo:"ცხრა",                        ru:"девять",                              en:"nine"},
  {topic:"numbers", num:10,   meg:"ვითი",       tr:"viti",        geo:"ათი",                         ru:"десять",                              en:"ten"},
  {topic:"numbers", num:20,   meg:"ეჩი",        tr:"eči",         geo:"ოცი",                         ru:"двадцать",                            en:"twenty"},
  {topic:"numbers", num:30,   meg:"ეჩდოვითი",   tr:"ečdoviti",    geo:"ოცდაათი",                     ru:"тридцать",                            en:"thirty"},
  {topic:"numbers", num:100,  meg:"ოში",        tr:"oši",         geo:"ასი",                         ru:"сто",                                 en:"hundred"},
  {topic:"numbers", num:1000, meg:"ანთასი",     tr:"antasi",      geo:"ათასი",                       ru:"тысяча",                              en:"thousand"},
];
